name: Build Binaries

on:
  push:
    branches:
      - main1
  pull_request:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1
    strategy:
      matrix:
        GOOS: ["linux", "darwin", "windows"]
        GOARCH: ["amd64", "arm64"]
    steps:
      - uses: Chik-Network/actions/git-mark-workspace-safe@main

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Binary
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chik-tools-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: ${{ github.workspace }}/bin/chik-tools*

  installers:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        GOOS: ["linux"]
        GOARCH: ["amd64", "arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Env
        uses: Chik-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install fpm
        run: sudo gem install fpm

      - uses: actions/download-artifact@v4
        with:
          name: chik-tools-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: artifacts

      - name: Generate .deb
        run: |
          chmod +x artifacts/chik-tools
          fpm \
            --input-type dir \
            --output-type deb \
            --name chik-tools \
            --architecture ${{ matrix.GOARCH }} \
            --version "${{ env.RELEASE_TAG || github.run_number }}" \
            --url "https://github.com/Chik-Network/chik-tools" \
            --maintainer "Chik Network Inc <hello@chiknetwork.com>" \
            --description "Collection of CLI tools for working with Chik Blockchain" \
            artifacts/chik-tools=/usr/local/bin/chik-tools
          mkdir -p installer-out
          mv *.deb installer-out/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer-chik-tools-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: ${{ github.workspace }}/installer-out/*.deb

  release:
    runs-on: ubuntu-latest
    needs:
      - installers
    steps:
      - uses: actions/checkout@v4

      - name: Set Env
        uses: Chik-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show artifacts
        run: tree artifacts

      - name: Generate artifact zips
        if: env.RELEASE == 'true'
        run: |
          cd ${{ github.workspace }}/artifacts || exit 1
          DIRS=$(find . -type d -name 'chik-tools*')
          while IFS= read -r dir; do
            echo "Creating zip for $dir..."
            zip -r $dir.zip $dir
          done <<< "$DIRS"

      - name: Upload Release Artifacts
        if: env.RELEASE == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILES=$(find ${{ github.workspace }}/artifacts -type f -name 'chik-tools*.zip')
          while IFS= read -r file; do
            gh release upload \
              $RELEASE_TAG \
              $file
          done <<< "$FILES"

          gh release upload \
            $RELEASE_TAG \
            artifacts/installer-chik-tools*/*.deb

      - uses: Chik-Network/actions/github/glue@main
        if: env.FULL_RELEASE == 'true' && '1' == '2'
        with:
          json_data: '{"release_version":"${{ env.RELEASE_TAG }}"}'
          glue_url: ${{ secrets.GLUE_API_URL }}
          glue_project: "chik-tools"
          glue_path: "trigger"
