name: Build Docker Images

on:
  push:
    branches:
      - main1
    tags:
      - '**'
  pull_request:

jobs:
  package:
    uses: Chik-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      push: ${{ github.event_name != 'pull_request' }}
